# Generated by Django 3.2 on 2022-04-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Write a short summary of your recipe here'),
        ),
    ]
